[0m14:49:48.438364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a7ec10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ae55e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ae5910>]}


============================== 14:49:48.449636 | ad985b3a-14f0-45ff-aac8-a12e949633a9 ==============================
[0m14:49:48.449636 [info ] [MainThread]: Running with dbt=1.10.2
[0m14:49:48.450832 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/melissanicholas/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed --full-refresh', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:49:48.451766 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/melissanicholas/ecommerce-subscription-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:49:48.454377 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.14511737, "process_in_blocks": "0", "process_kernel_time": 0.380471, "process_mem_max_rss": "93585408", "process_out_blocks": "0", "process_user_time": 2.296611}
[0m14:49:48.455233 [debug] [MainThread]: Command `dbt seed` failed at 14:49:48.455023 after 0.15 seconds
[0m14:49:48.455904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a7ec10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ae5430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ae5730>]}
[0m14:49:48.456560 [debug] [MainThread]: Flushing usage events
[0m14:49:48.833535 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:49:51.567042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bf0cc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cf746a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cf749d0>]}


============================== 14:49:51.576162 | b8dd4980-31bc-4213-aecf-ad58b7d5885c ==============================
[0m14:49:51.576162 [info ] [MainThread]: Running with dbt=1.10.2
[0m14:49:51.577155 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/melissanicholas/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:49:51.578033 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/melissanicholas/ecommerce-subscription-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:49:51.579578 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.122461654, "process_in_blocks": "0", "process_kernel_time": 0.205503, "process_mem_max_rss": "93466624", "process_out_blocks": "0", "process_user_time": 2.197466}
[0m14:49:51.580331 [debug] [MainThread]: Command `dbt run` failed at 14:49:51.580149 after 0.12 seconds
[0m14:49:51.580913 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bf0cc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cf740d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cf74100>]}
[0m14:49:51.581487 [debug] [MainThread]: Flushing usage events
[0m14:49:51.934026 [debug] [MainThread]: An error was encountered while trying to flush usage events
